name: "Super-Linter"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Super-Linter
      uses: github/super-linter@v4.8.5
