name: "Super-Linter"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        if: github.ref == 'FIXME'
        uses: super-linter/super-linter@4758be622215d0954c8353ee4877ffd60111cf8e # v6.4.1
        env:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: .
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: 'docs/photoswipe/.*'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}